spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driverClassName=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrations

#Mybatis configuration
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.example.demo.entities

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=user
spring.rabbitmq.password=password

rabbitmq.queue.accounts=accounts_queue
rabbitmq.queue.transactions=transactions_queue
rabbitmq.queue.account.balances=account_balances_queue
rabbitmq.exchange.name=project_exchange
rabbitmq.routing.key.accounts=accounts_routing_key
rabbitmq.routing.key.transactions=tranasctions_routing_key
rabbitmq.routing.key.account.balances=account_balances_routing_key